((last-sort-comparer
  (bmkp-info-cp bmkp-gnus-cp bmkp-url-cp bmkp-local-file-type-cp)
  bmkp-alpha-p)
 (last-reverse-sort-p)
 (last-reverse-multi-sort-p)
 (last-latest-bookmark-alist)
 (last-bmenu-omitted-bookmarks)
 (last-bmenu-marked-bookmarks #1=#("Books.org" 0 9
				   (bmkp-full-record
				    (#1#
				     (filename . "~/org/Excitement/Books.org")
				     (buffer-name . "Books.org")
				     (front-context-string . "* Philosophy\n** ")
				     (rear-context-string)
				     (front-context-region-string)
				     (rear-context-region-string)
				     (visits . 0)
				     (time . #2=(20307 11574 3058))
				     (created . #2#)
				     (position . 11)
				     (end-position . 11)))))
 (last-bmenu-filter-function . bmkp-last-specific-buffer-alist-only)
 (last-bmenu-filter-pattern . #3="")
 (last-bmenu-title . "Buffer `Projects-list.org' Bookmarks")
 (last-bmenu-bookmark)
 (last-specific-buffer . "Projects-list.org")
 (last-specific-file . #3#)
 (last-bmenu-toggle-filenames . t)
 (last-bmenu-before-hide-marked-alist)
 (last-bmenu-before-hide-unmarked-alist)
 (last-bookmark-file . "/home/pradeep/.emacs.bmk"))
